###RECUPERAR TODOS LOS RESTAURANTES
GET http://localhost:3000/restaurants
###MOSTRAR TODOS LOS RESTAURANTES
GET http://localhost:3000/restaurants.html
###FILTRAR RESTAURANTES POR ID
GET http://localhost:3000/restaurants/2
###MOSTRAR MASSAGES
GET http://localhost:3000/massages
###RECUPERAR TODAS LAS IMAGENES DL RESTAURANTE SELECCIONADO
GET http://localhost:3000/restaurants/1/images
###enviar una nueva pelicula
POST http://localhost:3000/movies
Content-Type: application/json

  {
    "title": "PAWIS",
    "year": 2007,
    "director": "Lu castelo",
    "duration": 100,
    "poster": "https://img.fruugo.com/product/7/41/14532417_max.jpg",
    "genre": [
      "Action",
      "Adventure",
      "Sci-Fi"
    ],
    "rate": 10
  }
###enviarr una nueva pelicula
POST http://localhost:3000/movies
Content-Type: application/json

  {
    "title": "pirrin",
    "year": 2010,
    "director": "pawis",
    "duration": 130,
    "poster": "https://img.fruugo.com/product/7/41/14532417_max.jpg",
    "genre": [
      "Action",
      "Adventure",
      "Sci-Fi"
    ],
    "rate": 8.8
  }

###EDITAR PELICULA POR ID
PATCH  http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "title": "horacio come bananas",
  "year": 1969
}